import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderNav from '../HeaderNav'
import { Suspense } from 'react'
import LoadingSkeleton from '../Components/LoadingSkeleton'
import SideNav from '../SideNav'
import Notifications from '../Components/Notifications/NotificationModal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (  
    <html lang="en" data-theme="corporate">
      
      <body className={inter.className}>
        <HeaderNav/>
        
        <div className="flex justify-between w-full">  
            <SideNav/> 
            <Suspense fallback={<LoadingSkeleton/>}>
            {children}
            </Suspense>
        </div>
            
        </body>
    </html>
  )
}
